### ISSUE TITLE
Instructors must be able to manage courses

### ISSUE THREAD

**Issue by JadeFerguson** [JadeFerguson/TeachingCode#1]
Instructors should have full CRUD functionality for courses

- [ ] Add Instructor Role
- [ ] Instructors can create a Course (Title/Description/Video Lectures)
- [ ] Instructors can Edit a Course
- [ ] Instructors can Delete a Course
- [ ] Instructors have a landing page for all courses
- [ ] Only Instructors can Edit/Delete/Create Courses
